### PR TITLE
Fix comparison function for multi-matches

### PR DESCRIPTION
**Pull request by bitti**
I lost several games because some guesses which have at least two of the same letter are sometimes not reported correctly. For example:

```elisp
(wordel--comparison-orig "kebab" "abbey")
(#("k" 0 1 (hint wordel-guessed)) #("e" 0 1 (hint wordel-almost)) #("b" 0 1 (hint wordel-correct)) #("a" 0 1 (hint wordel-almost)) #("b" 0 1 (hint wordel-guessed)))
```

The last `hint` `wordel-guessed` should be a `wordel-almost` because target word contains two 'b'. It seems the root cause lies in the condition `(not (member g matches))` which checks if we already have a match for this character, but having a matching character doesn't mean there could be a second one of the same.

So I rewrote the logic to first collect all potential 'almost matches' (called `non-matches` in the code) which is then used to find all almost matches.

Even though not strictly necessary, I also rewrote the `cl-loop` into a `cl-mapcar` for a better match with my newly introduced `cl-mapc` form.

For a more quantitative test, I collected more test cases in the following `org-mode` text. The current implementation fails several of them (although for the `keeps`, `abbey` pair it's because it's somewhat arbitrary which of the two `e`'s is the "almost match"):

```
#+name: Testcases
| guess | answer | score      | type   |
|-------+--------+------------+--------|
| skill | brave  | ⬜⬜⬜⬜⬜ | none   |
| crane | crane  | 🟩🟩🟩🟩🟩 | solved |
| crank | crane  | 🟩🟩🟩🟩⬜ | almost |
| skull | rebus  | 🟨⬜🟨⬜⬜ | normal |
| adobe | adage  | 🟩🟩⬜⬜🟩 | normal |
| quiet | serif  | ⬜⬜🟨🟨⬜ | normal |
| radix | raise  | 🟩🟩⬜🟨⬜ | normal |
| canon | xenon  | ⬜⬜🟩🟩🟩 | multi  |
| kebab | abbey  | ⬜🟨🟩🟨🟨 | multi  |
| babes | abbey  | 🟨🟨🟩🟩⬜ | multi  |
| abyss | abbey  | 🟩🟩🟨⬜⬜ | multi  |
| algae | abbey  | 🟩⬜⬜⬜🟨 | multi  |
| keeps | abbey  | ⬜🟨⬜⬜⬜ | multi  |
| abate | abbey  | 🟩🟩⬜⬜🟨 | multi  |
| train | xenon  | ⬜⬜⬜⬜🟩 | multi  |

#+begin_src elisp :var cases=Testcases :results output
(defun compare-guess-subject (guess subject)
  (mapconcat
   'identity
   (mapcar
    (lambda (p)
      (case (cadr (text-properties-at 0 p))
        (wordel-correct "🟩")
        (wordel-almost "🟨")
        (wordel-guessed "⬜")))
    (wordel--comparison guess subject))))

(mapc
 (lambda (testcase)
   (seq-let (guess subject expected) testcase
     (eval
      `(ert-deftest ,(intern (concat "matches-" guess "-" subject)) ()
         (should (equal (compare-guess-subject ,guess ,subject)
                        ,expected))))))
 cases)
(ert t)
#+end_src
```

### CODE REVIEW

**Comment by progfolio** [comment]
Thanks for bringing this to my attention.
Whichever game I referenced for the rule set must've behaved differently.
Does the following implementation work for you?:

```emacs-lisp
(defun wordel--comparison (guess subject)
  "Return propertized GUESS character list compared against SUBJECT."
  (cl-loop with guesses =  (split-string guess "" 'omit-nulls)
           with matches = nil
           for i from 0 to (1- (length guesses))
           for g = (nth i guesses)
           for match = (setf (alist-get g matches nil t #'equal)
                             (string-match-p g subject (1+ (alist-get g matches -1 nil #'equal))))
           collect (propertize g 'hint (if (not match)
                                           'wordel-guessed
                                         (if (or (eq match i)
                                                 (equal (char-to-string (aref subject i)) g))
                                             'wordel-correct
                                           'wordel-almost)))))
```

**Comment by bitti** [comment]
> Does the following implementation work for you?

It passes my test cases fine and may be better than my solution by doing everything in a single for loop.

I couldn't look through how the implementation works, but I'd simplify it a bit by generating the index implicitly:

```diff
-          for i from 0 to (1- (length guesses))
-          for g = (nth i guesses)
+          for i from 0
+          for g in guesses
```

That also avoids calling `nth` repeatedely on a list.

**Comment by progfolio** [comment]
> I'd simplify it a bit by generating the index implicitly

Good point. I've pushed something similar.
Should be fixed on main branch. Let me know if you run into any other failing cases. Thanks.

**Comment by bitti** [comment]
I'm sorry it turns out my test cases were insuffient. I looked through your solution and noticed that you look forward to find a potential 'almost match' without considering that there may be a correct guess for the same letter. So I came up with some more test cases to exemplify the problem:

```
| allay | telos  | ⬜⬜🟩⬜⬜ | multi  |
| allyl | telos  | ⬜⬜🟩⬜⬜ | multi  |
| allee | telos  | ⬜⬜🟩🟨⬜ | multi  |
```

The corresponding results with the current code are:

```
| allay | telos  | ⬜🟨⬜⬜⬜ |
| allyl | telos  | ⬜🟨⬜⬜🟨 |
| allee | telos  | ⬜🟨⬜🟨⬜ |
```

As you can see in all 3 cases the `l` is matched as an `almost` match in 2nd position, even though it should be a correct match in 3rd position. In the second example, the `l` is even matched twice. While the previous code had problems when a guess was at a later position than several of the same letter in the subject, it's the other way around this time. Though, I think the matching logic should be order independent.

**Comment by bitti** [comment]
In case you're interested: I rewrote my solution with two `cl-loop`s:

```elisp
(defun wordel--comparison (guess subject)
  "Return propertized GUESS character list compared against SUBJECT."
  (cl-loop with non-matches = (cl-loop for s across subject
                                       for g across guess
                                       unless (= g s)
                                       collect s)
           for s across subject
           for g across guess
           collect (propertize (string g) 'hint (if (= g s)
                                                    'wordel-correct
                                                  (if-let ((i (cl-position g non-matches)))
                                                      (progn
                                                        (pop (nthcdr i non-matches))
                                                        'wordel-almost)
                                                    'wordel-guessed)))))
```

On this occasion I learned that there is an [`across` clause](https://www.gnu.org/software/emacs/manual/html_node/cl/For-Clauses.html) which can directly iterate over strings, that happily leads to some simplifications. Still, you may find a simpler solution.

**Comment by bitti** [comment]
While my implementation can probably still be improved, I suppose correctness is what matters most. Therefore, I opened another PR with my proposal (see #13).

**Pull request closed without merging**
